//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsTimeAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class news_timeEntities3 : DbContext
    {
        public news_timeEntities3()
            : base("name=news_timeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Estados_tiempo> Estados_tiempo { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
    }
}
