//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsTimeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados_tiempo
    {
        public int IdTeam { get; set; }
        public Nullable<System.DateTime> observation_time { get; set; }
        public Nullable<int> temperature { get; set; }
        public string weather_descriptions { get; set; }
        public string wind_speed { get; set; }
        public string wind_degree { get; set; }
        public string wind_dir { get; set; }
        public string pressure { get; set; }
        public string precip { get; set; }
        public string humidity { get; set; }
        public string cloudcover { get; set; }
        public string feelslike { get; set; }
        public string uv_index { get; set; }
        public string visibility { get; set; }
        public Nullable<int> IDCiudad { get; set; }
    }
}
