//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsTimeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int Idnoticia { get; set; }
        public string autor { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string urlToImage { get; set; }
        public Nullable<System.DateTime> publishedAt { get; set; }
        public string content { get; set; }
        public Nullable<int> IDCiudad { get; set; }
    }
}
